name: Docker Build Workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run the Unit test cases
        run: echo "Running Unit test cases"
      - name: "owasp dependnecy Check"
        run: "Running Owasp Dependecy Check"
